# After staring container, don't forget to install db :
#   docker exec -it airnotifier python /airnotifier/install.py

version: "3"
services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file: .mongo.env

  airnotifier:
    image: airnotifier
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - ./certs:/var/airnotifier/pemdir
      - ./logs:/var/log/airnotifier
    ports:
      - 8801:8801
    env_file: .env
